Disable the X-XSS-Protection header in defaults #35
ring-clojure/ring-defaults pull request #36
Opened 2021-03-23 13:38 UTC by mahsa2

Disable the XSS Auditor in older browsers by default.
The X-XSS-Protection header has been deprecated by modern browsers due to security issues it introduces on the client-side.

Resolves: #35

2021-03-23 16:31 UTC, weavejester requested changes

2021-03-23 16:31 UTC, weavejester commented on README.md
> -
Let's save formatting changes for another PR.

2021-03-23 16:31 UTC, weavejester commented on README.md
> +    Disable the X-XSS-Protection header that tells old browsers to
This should probably be something more like:

```
**Deprecated.** Enable the X-XSS-Protection header. This is no longer
considered best practice by OWASP and should be avoided.
See: [wrap-xss-protection][10].
```

2021-03-24 11:39 UTC, mahsa2 commented
Thanks for the review. Submitted an update.

2021-03-28 11:57 UTC, weavejester commented
That seems fine. Can you squash your two commits?

2021-04-23 05:47 UTC, weavejester commented
Thanks! Apologies for the delay - GitHub doesn't always notify me about commit changes.

Can you change the commit message to:

```
Disable the X-XSS-Protection header in defaults

Disable the XSS Auditor in older browsers by default. The
X-XSS-Protection header has been deprecated by modern browsers due to
security issues it introduces on the client.

See: https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#x-xss-protection-header

Fixes #35.
```

That just fixes the wrapping, and I tend to use 'Fixes' rather than 'Resolves' in the logs, so by making it consistent it's easier to search. Adding the URL gives some information on why the change was implemented.

2022-09-19 16:31 UTC, terop commented
This PR could probably be closed as the change has been done in another PR.

2022-09-19 22:29 UTC, closed without merging